services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./.docker_volumes/data/:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - postgres-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=${POSTGRES_USER}",
          "--dbname=${POSTGRES_DB}",
        ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
  server:
    build:
      context: .
      target: final
    env_file:
      - .env
    environment:
      - POSTGRES_HOSTNAME=database
    depends_on:
      database:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge
